### ISSUE TITLE
Uncaught TypeError: m.vclock is not a function

### ISSUE THREAD

**Issue by crofty** [aredington/schism#1]
Hi, I'm just starting to explore this library and I ran into an issue.  I'm trying to converge two maps in cljs but I'm getting the error `Uncaught TypeError: m.vclock is not a function`

I think the following needs to be `(.-vclock m)` instead of `(.vclock m)`

https://github.com/aredington/schism/blob/a90a0a849703ad80607dcea947b64194bf02f448/src/schism/impl/types/map.cljc#L225

**Comment by aredington** [comment]
Should be fixed in 41e7d8b3e440551aec234a5cc34b6d534d733ad2

I've got a few more things to mess with but will cut a release soon
